Repository Cleymax/BookmarksBox, pull requests merged in 2021-05, with the labels that each got.

#29 👷 Add CI
  .github/workflows/nodejs.yml
  .github/workflows/php.yml
  .github/workflows/sonar.yml
  composer.json
  composer.lock
  package.json
  sonar-project.properties
Labels: CI

#28 👷 Add Dependabot
  .github/dependabot.yml
  App/Bootstrap.php
  App/Controllers/AuthController.php
  App/Controllers/Controller.php
  App/Router/Router.php
  App/Tools/Http.php
  App/services/UploaderService.php
  bb
  public/upload/.gitkeep
  resources/layouts/parts/head.php
  resources/layouts/parts/header.php
Labels: CI

#30 🚀 Fix bug, security
  App/Api/TeamsApiController.php
  App/Controllers/AuthController.php
  App/Controllers/Controller.php
  App/Router/Route.php
  App/Router/Router.php
  App/Security/Auth.php
  App/Tools/Http.php
  App/services/UploaderService.php
  composer.json
  resources/js/elements/Skeleton.js
  resources/scss/app.scss
  resources/views/auth/login.php
  resources/views/auth/password-forgot.php
Labels: bug, enhancement

#26 :bug: Fix bug of editing and adding bookmarks
  App/Controllers/BookmarkController.php
  App/Controllers/DashboardController.php
  App/Controllers/UserController.php
  App/Models/Bookmarks.php
  resources/scss/app.scss
  resources/scss/modules/_button.scss
  resources/scss/page/_home.scss
  resources/scss/page/teams/_dashboard.scss
  resources/views/dashboard.php
  resources/views/settings.php
  resources/views/teams/all.php
Labels: enhancement

#32 Add navbar, teams, invitation
  App/Controllers/DashboardController.php
  App/Controllers/TeamsController.php
  App/Database/Query.php
  App/Helper/TeamHelper.php
  App/Models/Bookmarks.php
  App/Models/Teams.php
  App/Models/User.php
  public/index.php
  resources/js/Teams.js
  resources/js/app.js
  resources/js/dom.js
  resources/js/elements/Alert.js
  resources/js/elements/Tooltip.js
  resources/js/window.js
  resources/layouts/dashboard.php
  resources/layouts/parts/head.php
  resources/scss/app.scss
  resources/scss/modules/_cards.scss
  resources/scss/modules/_flex.scss
  resources/scss/modules/_materialboxed.scss
  resources/scss/modules/_popup.scss
  resources/scss/modules/_table.scss
  resources/scss/modules/_tabs.scss
  resources/scss/modules/_tooltip.scss
  resources/scss/page/_dashboard.scss
  resources/scss/page/_teams.scss
  resources/scss/tools/_typography.scss
  resources/views/dashboard.php
  resources/views/favorite.php
  resources/views/teams/all.php
  resources/views/teams/dashboard.php
  resources/views/teams/invite.php
  resources/views/teams/manager.php
Labels: enhancement

#33 Update Teams
  App/Controllers/BookmarkController.php
  App/Controllers/TeamsController.php
  App/Models/Teams.php
  App/Router/Router.php
  App/Tools/Http.php
  composer.lock
  public/img/cat-404.gif
  public/index.php
  resources/js/app.js
  resources/layouts/dashboard.php
  resources/layouts/parts/head.php
  resources/layouts/parts/header-dashboard.php
  resources/scss/modules/_button.scss
  resources/scss/modules/_card.scss
  resources/scss/modules/_cards.scss
  resources/scss/page/_dashboard.scss
  resources/scss/page/_teams.scss
  resources/views/404.php
  resources/views/dashboard.php
  resources/views/favorite.php
  resources/views/teams/all.php
  resources/views/teams/leave.php
Labels: enhancement

#31 🚀 Add CAS authentication
  .env.example
  .github/workflows/php.yml
  App/Controllers/AuthController.php
  App/Security/Auth.php
  App/services/CasAuthService.php
  composer.json
  composer.lock
  public/index.php
  resources/views/auth/login.php
Labels: enhancement

#34 :rocket: Modified Settings parameters
  App/Api/BookmarksApiController.php
  App/Controllers/DashboardController.php
  App/Controllers/SettingsController.php
  App/Controllers/UserController.php
  App/Models/Folders.php
  public/index.php
  resources/js/app.js
  resources/layouts/dashboard.php
  resources/layouts/parts/header-dashboard.php
  resources/layouts/security.php
  resources/layouts/settings.php
  resources/scss/page/_dashboard.scss
  resources/scss/page/_home.scss
  resources/scss/page/_settings.scss
  resources/views/dashboard.php
  resources/views/profil.php
  resources/views/settings.php
  resources/views/settings/2fa.php
  resources/views/settings/biography.php
  resources/views/settings/delete.php
  resources/views/settings/email.php
  resources/views/settings/identity.php
  resources/views/settings/infos.php
  resources/views/settings/password.php
  resources/views/settings/profil_picture.php
  resources/views/settings/security.php
  tests/api.http
Labels: enhancement
