Repository Cleymax/BookmarksBox, pull requests merged in 2021-06, with the labels that each got.

#35 Fix menu, add manage team
  .editorconfig
  App/Api/BookmarkApiController.php
  App/Api/TeamsApiController.php
  App/Api/UserApiController.php
  App/Controllers/AuthController.php
  App/Controllers/Controller.php
  App/Controllers/TeamsController.php
  App/Database/QueryApi.php
  App/Database/migration/1622469727_description_team.php
  App/Database/migration/1622650599_bookmarks_views.php
  App/Helper/TeamHelper.php
  App/Models/Model.php
  App/Models/Teams.php
  App/Router/Router.php
  App/Security/Auth.php
  App/Tools/Http.php
  bb
  package-lock.json
  package.json
  public/index.php
  resources/js/CopyClipboard.js
  resources/js/admin.js
  resources/js/api.js
  resources/js/app.js
  resources/js/dom.js
  resources/js/elements/FilesUploader.js
  resources/js/tab.js
  resources/js/table.js
  resources/js/team.js
  resources/js/window.js
  resources/layouts/dashboard.php
  resources/layouts/security.php
  resources/scss/app.scss
  resources/scss/modules/_animations.scss
  resources/scss/modules/_cards.scss
  resources/scss/modules/_filesupload.scss
  resources/scss/modules/_flex.scss
  resources/scss/modules/_margin.scss
  resources/scss/modules/_select.scss
  resources/scss/modules/_swa2.scss
  resources/scss/modules/_table.scss
  resources/scss/modules/_tabs.scss
  resources/scss/page/_dashboard.scss
  resources/scss/page/_profil.scss
  resources/scss/page/_teams.scss
  resources/scss/tools/_typography.scss
  resources/views/favorite.php
  resources/views/settings/profil_picture.php
  resources/views/teams/all.php
  resources/views/teams/dashboard.php
  resources/views/teams/manager.php
  resources/views/user/2fa.php
  tests/api.http
  yarn.lock
Labels: enhancement

#38 Add teams, delete, remove invitation ...
  .env.example
  .gitignore
  App/Controllers/AuthController.php
  App/Controllers/Controller.php
  App/Controllers/TeamsController.php
  App/Controllers/UserController.php
  App/Database/Database.php
  App/Database/migration/1622991492_team_update_public_col.php
  App/Exceptions/FileUploadException.php
  App/Helper/TeamHelper.php
  App/Helper/UserHelper.php
  App/Models/Teams.php
  App/services/FileUploader.php
  App/services/IdenticonService.php
  composer.json
  composer.lock
  public/index.php
  resources/js/elements/Alert.js
  resources/js/team.js
  resources/layouts/dashboard.php
  resources/scss/app.scss
  resources/scss/modules/_infopoint.scss
  resources/views/settings/profil_picture.php
  resources/views/teams/all.php
  resources/views/teams/create.php
  resources/views/teams/manager.php
Labels: enhancement, wontfix

#39 Add Menu
  .env.example
  App/Api/FolderApiController.php
  App/Controllers/Controller.php
  App/Router/Route.php
  App/Router/Router.php
  App/services/RateLimitService.php
  composer.json
  composer.lock
  public/index.php
  resources/js/CopyClipboard.js
  resources/js/api.js
  resources/js/app.js
  resources/js/elements/FilesUploader.js
  resources/js/elements/FolderMenuRow.js
  resources/scss/modules/_filesupload.scss
  resources/views/teams/all.php
  resources/views/teams/manager.php
Labels: enhancement

#40 Fix bug redis
  .env.example
  App/Controllers/Controller.php
  App/Router/Route.php
  App/Router/Router.php
  App/Tools/Http.php
  resources/js/app.js
  resources/scss/page/_home.scss
  resources/views/favorite.php
  resources/views/teams/dashboard.php
Labels: bug

#43 :rocket: Barre informations bookmarks
  resources/js/app.js
  resources/js/dashboard.js
  resources/scss/page/_home.scss
  resources/views/dashboard.php
Labels: enhancement

#44 Optimization, update style
  resources/js/api.js
  resources/js/dashboard.js
  resources/layouts/dashboard.php
  resources/scss/modules/_grid.scss
  resources/scss/page/_dashboard.scss
  resources/scss/page/_home.scss
  resources/scss/page/_settings.scss
  resources/views/dashboard.php
  resources/views/favorite.php
Labels: bug, enhancement

#45 :bug: Fix Bug Using Right Click Menu, add Move Menu
  App/Api/BookmarkApiController.php
  package.json
  public/index.php
  resources/js/api.js
  resources/js/dashboard.js
  resources/layouts/parts/header-dashboard.php
  resources/scss/page/_home.scss
  resources/views/dashboard.php
  yarn.lock
Labels: enhancement

#46 Compatibility univ server
  App/Api/TeamsApiController.php
  App/Controllers/TeamsController.php
  App/Exceptions/MissingAccessException.php
  App/Helper/TeamHelper.php
  App/Tools/Array.php
  resources/js/api.js
  resources/js/dashboard.js
  resources/js/elements/FolderMenuRow.js
  resources/layouts/dashboard.php
  resources/layouts/parts/footer.php
  resources/views/teams/dashboard.php
  resources/views/teams/manager.php
Labels: bug, documentation, enhancement

#47 Scrapper, Fix pofile, add teams folder and bookmarks
  App/Api/ScrapingApiController.php
  App/Controllers/Controller.php
  App/Controllers/SettingsController.php
  App/Controllers/TeamsController.php
  App/Controllers/UserController.php
  App/Database/migration/1623787145_bookmark_team_id.php
  App/Helper/BookmarkHelper.php
  App/Models/Bookmarks.php
  App/Models/Folders.php
  App/Models/User.php
  App/Security/Auth.php
  App/services/ScraperService.php
  composer.json
  composer.lock
  public/index.php
  resources/js/app.js
  resources/layouts/dashboard.php
  resources/layouts/parts/footer.php
  resources/scss/modules/_infopoint.scss
  resources/scss/page/_dashboard.scss
  resources/scss/page/_home.scss
  resources/scss/page/_profil.scss
  resources/views/favorite.php
  resources/views/home.html
  resources/views/info.html
  resources/views/profil.php
  resources/views/settings/password.php
  resources/views/teams/dashboard.php
Labels: bug, enhancement

#48 :rocket: Move Menu, Bookmark Info editing, fix bug
  App/Api/BookmarkApiController.php
  public/index.php
  resources/js/api.js
  resources/js/app.js
  resources/js/dashboard.js
  resources/js/elements/FolderMenuRow.js
  resources/layouts/dashboard.php
  resources/scss/page/_dashboard.scss
  resources/views/dashboard.php
  webpack.common.js
Labels: enhancement

#49 Raph
  App/Api/BookmarkApiController.php
  App/Api/FolderApiController.php
  App/Database/migration/1623947358_bookmark_description.php
  App/Models/Folders.php
  composer.lock
  public/index.php
  resources/js/api.js
  resources/js/app.js
  resources/js/dashboard.js
  resources/views/dashboard.php
Labels: enhancement

#50 :rocket: Adding function to create folder
  App/Api/FolderApiController.php
  App/Controllers/FolderController.php
  public/index.php
  resources/js/api.js
  resources/js/dashboard.js
  resources/layouts/parts/footer.php
  resources/views/dashboard.php
Labels: enhancement

#51 Fix bug
  App/Models/Teams.php
  App/Security/Auth.php
  App/Tools/Http.php
  public/index.php
  resources/js/api.js
  resources/js/app.js
  resources/js/dashboard.js
  resources/js/elements/FolderMenuRow.js
  resources/layouts/parts/head.php
  resources/scss/modules/_cards.scss
  resources/scss/modules/_filesupload.scss
  resources/scss/page/_home.scss
  resources/views/auth/login.php
  resources/views/dashboard.php
  resources/views/favorite.php
  resources/views/folder.php
  resources/views/profil.php
  resources/views/teams/all.php
  resources/views/teams/create.php
  resources/views/teams/manager.php
Labels: bug, dependencies, documentation, duplicate, enhancement

#55 :tada: Fix bug
  App/Api/BookmarkApiController.php
  App/Api/FolderApiController.php
  App/Api/TeamsApiController.php
  App/Controllers/SettingsController.php
  App/Controllers/TeamsController.php
  App/Helper/TeamHelper.php
  App/Models/Folders.php
  App/Models/Teams.php
  public/index.php
  resources/js/api.js
  resources/js/dashboard.js
  resources/js/elements/FolderMenuRow.js
  resources/layouts/dashboard.php
  resources/layouts/parts/footer.php
  resources/views/favorite.php
  resources/views/search.php
  resources/views/settings/delete.php
  resources/views/settings/identity.php
  resources/views/teams/all.php
  resources/views/teams/dashboard.php
  resources/views/user/2fa.php
Labels: bug, documentation, enhancement
